//! Browser-based first-run setup, served in place of the API when no `wallet.toml` exists yet.
//!
//! Before this existed, standing the service up meant hand-writing ~30 TOML fields, generating
//! a BIP32 key by hand with an external tool, and getting three xpubs and their derivation
//! paths exactly right with no feedback until `serve` failed. On Umbrel - which has no
//! per-app file editor and no secret-entry UI - that meant SSHing into the box. This module
//! replaces that with a wizard on the app's own port.
//!
//! It deliberately reuses `wizard.rs` rather than duplicating it: the same [`WizardAnswers`]
//! struct, the same field validators, and the same `render_user_toml` renderer that
//! `cosigner init` uses. The web layer here is only collection and IO, so the CLI and the
//! browser can't drift into producing different configs.
//!
//! # Lifecycle
//!
//! `docker-entrypoint.sh` runs `cosigner setup` when `config/wallet.toml` is absent, and
//! `cosigner serve` when it's present. Finishing the wizard writes the config and then, on an
//! explicit click, shuts this server down; Docker's `restart: unless-stopped` brings the
//! container back, the entrypoint now finds a config, and the real API starts. There is no
//! in-process transition from setup mode to serving mode - a restart is the only path, so a
//! half-configured process can never end up holding a signing key.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use anyhow::{Context, Result};
use axum::extract::State;
use axum::http::StatusCode;
use axum::response::{Html, IntoResponse, Response};
use axum::routing::{get, post};
use axum::{Json, Router};
use bitcoin::bip32::{DerivationPath, Xpriv, Xpub};
use bitcoin::secp256k1::rand::RngCore;
use bitcoin::secp256k1::Secp256k1;
use serde::{Deserialize, Serialize};
use tokio::sync::{oneshot, Mutex};
use zeroize::Zeroizing;

use nostr_sdk::ToBech32;

use crate::config::{ChainNetwork, WalletConfig};
use crate::descriptor;
use crate::wizard::{
    self, BitcoindAuthAnswer, KeyAnswer, NotifyAnswer, PolicyAnswer, ServerSigningAnswer,
    WizardAnswers,
};

/// Where the generated SERVER key is written, relative to the config directory. Referenced by
/// `[server_signing].xprv_file` in the config this module writes.
const SERVER_XPRV_FILENAME: &str = "server.xprv";
const WALLET_TOML_FILENAME: &str = "wallet.toml";
/// Bearer token for `/inspect` and `/sign_psbt`, generated here and referenced by
/// `[server].api_token_file` (which `docker-entrypoint.sh` emits).
const API_TOKEN_FILENAME: &str = "api.token";
/// Optional operator override for the bundled device-compatibility matrix. Absent is normal.
const COMPATIBILITY_FILENAME: &str = "compatibility.toml";
/// This service's Nostr secret key, generated by the wizard when the transport is enabled.
/// A machine credential, sited and permissioned exactly like `server.xprv`.
const NOSTR_NSEC_FILENAME: &str = "nostr.nsec";

/// Deployment facts the wizard doesn't ask about because the container already knows them.
/// These come from the same environment variables `docker-entrypoint.sh` reads, so the two
/// always agree about what the deployment looks like.
#[derive(Clone, Debug)]
pub struct Deployment {
    pub network: ChainNetwork,
    pub config_dir: PathBuf,
    pub data_dir: PathBuf,
    pub bind_addr: String,
    pub bitcoind_rpc_url: String,
}

/// A freshly generated SERVER key, held in memory between "generate" and "finish".
///
/// Only the account-level xprv is retained. The master key it was derived from is dropped
/// immediately after derivation and never persisted: every key the descriptor actually uses
/// hangs off unhardened `<0;1>/*` children of this account key, so the master buys nothing
/// operationally while being strictly more dangerous to keep.
struct GeneratedServerKey {
    /// Fingerprint of the *master* key - this is what goes in the descriptor's key origin.
    master_fingerprint: String,
    derivation_path: String,
    xpub: String,
    /// The account-level xprv, wiped on drop.
    account_xprv: Zeroizing<String>,
}

pub struct SetupState {
    deployment: Deployment,
    generated: Mutex<Option<GeneratedServerKey>>,
    /// Fires once, when the user clicks "start the cosigner" on the final screen.
    shutdown: Mutex<Option<oneshot::Sender<()>>>,
}

impl SetupState {
    pub fn new(deployment: Deployment, shutdown: oneshot::Sender<()>) -> Self {
        Self {
            deployment,
            generated: Mutex::new(None),
            shutdown: Mutex::new(Some(shutdown)),
        }
    }

    fn wallet_toml_path(&self) -> PathBuf {
        self.deployment.config_dir.join(WALLET_TOML_FILENAME)
    }

    fn server_xprv_path(&self) -> PathBuf {
        self.deployment.config_dir.join(SERVER_XPRV_FILENAME)
    }

    fn api_token_path(&self) -> PathBuf {
        self.deployment.config_dir.join(API_TOKEN_FILENAME)
    }

    fn nostr_nsec_path(&self) -> PathBuf {
        self.deployment.config_dir.join(NOSTR_NSEC_FILENAME)
    }

    /// The compatibility matrix: an operator-supplied `compatibility.toml` in the config
    /// directory if there is one, otherwise the bundled copy. Reloaded per request rather than
    /// cached, so an operator correcting the matrix doesn't have to restart the wizard to see it
    /// take effect - this is a handful of TOML read once per setup, not a hot path.
    fn matrix(&self) -> Result<crate::compat::Matrix, SetupError> {
        crate::compat::Matrix::load_or_bundled(
            &self.deployment.config_dir.join(COMPATIBILITY_FILENAME),
        )
        .map_err(|e| SetupError::internal(format!("loading the compatibility matrix: {e}")))
    }
}

pub fn router(state: Arc<SetupState>) -> Router {
    Router::new()
        .route("/", get(index_handler))
        .route("/health", get(health_handler))
        .route("/api/state", get(state_handler))
        .route("/api/compat", get(compat_handler))
        .route("/api/compat/resolve", post(resolve_compat_handler))
        .route("/api/validate-key", post(validate_key_handler))
        .route("/api/server-key", post(server_key_handler))
        .route("/api/decode-qr", post(decode_qr_handler))
        .route("/api/finish", post(finish_handler))
        .route("/api/start", post(start_handler))
        // Axum's default request body cap is 2 MB; a phone photo of a QR is routinely larger.
        .layer(axum::extract::DefaultBodyLimit::max(12 * 1024 * 1024))
        .with_state(state)
}

// --- error plumbing ---------------------------------------------------------------------------

/// Every failure here is something the person at the keyboard needs to read and act on, so the
/// message is the payload rather than being swallowed into a generic 500.
struct SetupError(StatusCode, String);

impl IntoResponse for SetupError {
    fn into_response(self) -> Response {
        (self.0, Json(serde_json::json!({ "error": self.1 }))).into_response()
    }
}

impl SetupError {
    fn bad_request(msg: impl Into<String>) -> Self {
        Self(StatusCode::BAD_REQUEST, msg.into())
    }
    fn internal(msg: impl Into<String>) -> Self {
        Self(StatusCode::INTERNAL_SERVER_ERROR, msg.into())
    }
}

// --- handlers ---------------------------------------------------------------------------------

async fn index_handler() -> Html<&'static str> {
    Html(include_str!("setup.html"))
}

#[derive(Serialize)]
struct SetupHealth {
    service: &'static str,
    version: &'static str,
    status: &'static str,
    network: &'static str,
}

/// Answers on the same path the real API uses, so Umbrel's `app_proxy` port-wait and the
/// container HEALTHCHECK both succeed while the box is still waiting to be configured. The
/// `status` field is what distinguishes this from a configured, serving instance.
async fn health_handler(State(state): State<Arc<SetupState>>) -> Json<SetupHealth> {
    Json(SetupHealth {
        service: "cosigner",
        version: env!("CARGO_PKG_VERSION"),
        status: "awaiting-setup",
        network: wizard::network_str(state.deployment.network),
    })
}

#[derive(Serialize)]
struct StateResponse {
    network: &'static str,
    /// True once wallet.toml exists - the UI uses this to jump straight to the final screen if
    /// the page is reloaded after finishing.
    configured: bool,
    default_derivation_path: String,
    default_timelock_blocks: u16,
    bitcoind_rpc_url: String,
}

async fn state_handler(State(state): State<Arc<SetupState>>) -> Json<StateResponse> {
    Json(StateResponse {
        network: wizard::network_str(state.deployment.network),
        configured: state.wallet_toml_path().exists(),
        default_derivation_path: default_derivation_path(state.deployment.network),
        default_timelock_blocks: 12960,
        bitcoind_rpc_url: state.deployment.bitcoind_rpc_url.clone(),
    })
}

/// The compatibility matrix, for the device-selection step. Loaded from the config directory if
/// the operator has supplied one, otherwise the copy compiled into the binary.
async fn compat_handler(
    State(state): State<Arc<SetupState>>,
) -> Result<Json<crate::compat::Matrix>, SetupError> {
    Ok(Json(state.matrix()?))
}

#[derive(Deserialize)]
struct ResolveCompatRequest {
    hardware: String,
    coordinator: String,
    /// Defaults to the coordinator: one app commonly plays both roles.
    #[serde(default)]
    mobile_holder: Option<String>,
}

#[derive(Serialize)]
struct ResolveCompatResponse {
    resolution: crate::compat::Resolution,
    /// The exact text the operator must acknowledge, or `null` if nothing needs acknowledging.
    /// Generated from which capability check failed, never written per device pair - see
    /// `compat::Resolution::acknowledgement`.
    acknowledgement: Option<String>,
    /// Every device, each with its own verdict against this coordinator. Nothing is filtered out:
    /// a greyed-out option with no explanation produces support questions, an annotated one
    /// teaches the constraint.
    options: Vec<CompatOption>,
}

#[derive(Serialize)]
struct CompatOption {
    id: String,
    label: String,
    verdict: crate::compat::Verdict,
    notes: Option<String>,
    summary: Option<String>,
}

async fn resolve_compat_handler(
    State(state): State<Arc<SetupState>>,
    Json(req): Json<ResolveCompatRequest>,
) -> Result<Json<ResolveCompatResponse>, SetupError> {
    let matrix = state.matrix()?;
    let mobile_holder = req.mobile_holder.as_deref().unwrap_or(&req.coordinator);

    let resolution =
        crate::compat::resolve(&matrix, &req.hardware, &req.coordinator, mobile_holder)
            .map_err(|e| SetupError::bad_request(format!("{e}")))?;
    let options = crate::compat::options_for_coordinator(&matrix, &req.coordinator, mobile_holder)
        .map_err(|e| SetupError::bad_request(format!("{e}")))?
        .into_iter()
        .map(|(hw, res)| CompatOption {
            id: hw.id,
            label: hw.label,
            verdict: res.overall,
            notes: hw.notes,
            summary: res.acknowledgement(),
        })
        .collect();

    Ok(Json(ResolveCompatResponse {
        acknowledgement: resolution.acknowledgement(),
        resolution,
        options,
    }))
}

#[derive(Deserialize)]
struct ValidateKeyRequest {
    fingerprint: String,
    derivation_path: String,
    xpub: String,
}

#[derive(Serialize)]
struct ValidateKeyResponse {
    ok: bool,
}

/// Validates one key as it's typed, using the exact validators `cosigner init` uses - so the
/// browser rejects the same inputs the CLI would, with the same wording.
async fn validate_key_handler(
    State(state): State<Arc<SetupState>>,
    Json(req): Json<ValidateKeyRequest>,
) -> Result<Json<ValidateKeyResponse>, SetupError> {
    validate_key(state.deployment.network, &req)?;
    Ok(Json(ValidateKeyResponse { ok: true }))
}

fn validate_key(network: ChainNetwork, req: &ValidateKeyRequest) -> Result<KeyAnswer, SetupError> {
    let fingerprint = req.fingerprint.trim().to_lowercase();
    let derivation_path = req.derivation_path.trim().to_string();
    let xpub = req.xpub.trim().to_string();

    wizard::validate_fingerprint(&fingerprint).map_err(SetupError::bad_request)?;
    wizard::validate_derivation_path(&derivation_path).map_err(SetupError::bad_request)?;
    wizard::validate_xpub_for(network, &derivation_path)(&xpub).map_err(SetupError::bad_request)?;

    Ok(KeyAnswer {
        fingerprint,
        derivation_path,
        xpub,
    })
}

#[derive(Deserialize)]
struct ServerKeyRequest {
    /// Optional operator-supplied entropy - dice rolls, coin flips, anything they generated
    /// themselves - mixed into the OS CSPRNG output rather than replacing it. See
    /// [`generate_server_key`].
    #[serde(default)]
    user_entropy: Option<String>,
}

#[derive(Serialize)]
struct ServerKeyResponse {
    /// Whether the operator's own entropy went into this key, so the UI can say so plainly on
    /// the review screen instead of leaving them to remember.
    mixed_user_entropy: bool,
    master_fingerprint: String,
    derivation_path: String,
    xpub: String,
    /// `[fingerprint/path]xpub` - what another wallet needs to register this as a co-signer.
    key_expression: String,
    /// The same key expression as a scannable QR, for adding this key to a phone wallet without
    /// retyping it.
    key_expression_qr_svg: Option<String>,
    /// Coldcard's generic export shape, which a lot of wallets accept as a key-import file even
    /// when they don't parse a raw key expression. Offered as a fallback, not a preference.
    import_json: String,
}

/// Generates the SERVER key on the box, from the operating system's CSPRNG.
///
/// Entropy source: `bitcoin::secp256k1::rand::rngs::OsRng`, which on Linux is the
/// `getrandom(2)` syscall - the same kernel CSPRNG that seeds `/dev/urandom`, drawn directly
/// rather than through a file descriptor (so it cannot be affected by a missing or replaced
/// `/dev/urandom` node inside the container) and blocking until the pool is initialised. No
/// userspace PRNG is interposed, nothing is seeded from a timestamp, process id, or any other
/// low-entropy source, and no new dependency was added to reach it: secp256k1 already pulls
/// `rand` in this build.
///
/// 256 bits are drawn and used directly as BIP32 master seed material.
async fn server_key_handler(
    State(state): State<Arc<SetupState>>,
    body: Option<Json<ServerKeyRequest>>,
) -> Result<Json<ServerKeyResponse>, SetupError> {
    let network = state.deployment.network;
    let path_str = default_derivation_path(network);

    let user_entropy = body
        .and_then(|Json(b)| b.user_entropy)
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty());
    if let Some(extra) = &user_entropy {
        if extra.chars().count() < MIN_USER_ENTROPY_CHARS {
            return Err(SetupError::bad_request(format!(
                "extra entropy must be at least {MIN_USER_ENTROPY_CHARS} characters if supplied - \
                 a short string doesn't weaken the key, but it does invite false confidence. \
                 Roll dice, or leave it blank to use the OS CSPRNG alone"
            )));
        }
    }

    let generated = generate_server_key(network, &path_str, user_entropy.as_deref())
        .map_err(|e| SetupError::internal(format!("generating the SERVER key failed: {e}")))?;

    let expr = key_expression(
        &generated.master_fingerprint,
        &generated.derivation_path,
        &generated.xpub,
    );
    let response = ServerKeyResponse {
        mixed_user_entropy: user_entropy.is_some(),
        key_expression_qr_svg: qr_svg(&expr),
        import_json: serde_json::json!({
            "xfp": generated.master_fingerprint.to_uppercase(),
            "p2wsh": {
                "xpub": generated.xpub,
                "deriv": format!("m/{}", generated.derivation_path.replace('h', "'")),
                "_pub": generated.xpub,
            },
        })
        .to_string(),
        key_expression: expr,
        master_fingerprint: generated.master_fingerprint.clone(),
        derivation_path: generated.derivation_path.clone(),
        xpub: generated.xpub.clone(),
    };
    *state.generated.lock().await = Some(generated);
    Ok(Json(response))
}

/// Below this, supplied entropy is refused outright. It cannot *weaken* the key at any length -
/// the OS bytes are in the hash regardless - but accepting "abc" would let someone believe they
/// had protected themselves against a compromised RNG when they had not.
const MIN_USER_ENTROPY_CHARS: usize = 30;

/// Domain separation for the entropy mix, so this hash can never collide with any other use of
/// SHA-256 over similar material. Fixed forever.
const ENTROPY_MIX_TAG: &[u8] = b"bitme-cosigner/server-key/entropy-mix/v1";

/// Derives the SERVER key. `user_entropy`, if supplied, is *mixed with* the OS CSPRNG output -
/// never substituted for it.
///
/// The construction is `SHA256(tag || os_bytes || user_bytes)`, which is safe in both directions,
/// and that symmetry is the entire point:
///
/// - If the OS CSPRNG is sound, the output is unpredictable no matter what the user typed -
///   including something an attacker chose for them.
/// - If the OS CSPRNG is broken, backdoored, or returns a value an attacker already knows, the
///   output is *still* unpredictable to that attacker, because they would also have to guess the
///   user's contribution.
///
/// The second property is the one worth having. A hardware wallet shipping a build whose entropy
/// source had been quietly replaced is not a hypothetical, and no amount of reading *this* source
/// tells an operator what the binary on their box actually did. Dice they rolled themselves are
/// something they can verify without trusting this code at all.
///
/// With no user entropy the OS bytes are used directly, byte for byte as before - the default
/// path is unchanged rather than newly routed through a hash.
fn generate_server_key(
    network: ChainNetwork,
    path_str: &str,
    user_entropy: Option<&str>,
) -> Result<GeneratedServerKey> {
    use bitcoin::hashes::{sha256, Hash, HashEngine};

    let secp = Secp256k1::new();
    let path: DerivationPath = path_str
        .parse()
        .context("parsing the default derivation path")?;

    let mut os_bytes = Zeroizing::new([0u8; 32]);
    bitcoin::secp256k1::rand::rngs::OsRng.fill_bytes(os_bytes.as_mut());

    let seed: Zeroizing<[u8; 32]> = match user_entropy {
        None => os_bytes.clone(),
        Some(extra) => {
            let mut engine = sha256::Hash::engine();
            engine.input(ENTROPY_MIX_TAG);
            engine.input(os_bytes.as_ref());
            engine.input(extra.as_bytes());
            Zeroizing::new(sha256::Hash::from_engine(engine).to_byte_array())
        }
    };

    let master = Xpriv::new_master(network.xpub_network_kind(), seed.as_ref())
        .context("deriving a BIP32 master key from fresh entropy")?;
    let master_fingerprint = master.fingerprint(&secp).to_string().to_lowercase();

    let account = master
        .derive_priv(&secp, &path)
        .context("deriving the account key")?;
    let xpub = Xpub::from_priv(&secp, &account).to_string();

    Ok(GeneratedServerKey {
        master_fingerprint,
        derivation_path: path_str.to_string(),
        xpub,
        account_xprv: Zeroizing::new(account.to_string()),
    })
}

#[derive(Deserialize)]
struct FinishRequest {
    timelock_blocks: u16,
    /// Aliased for the same reason `KeysConfig::hardware` is: anything scripted against the old
    /// field name keeps working.
    #[serde(alias = "satochip")]
    hardware: ValidateKeyRequest,
    /// The SERVER key fingerprint this page was showing when the operator registered it. Checked
    /// against the key the service actually holds, so a regeneration between registering and
    /// finishing is caught rather than silently written. Optional so an older client still works.
    #[serde(default)]
    server_fingerprint: Option<String>,
    /// Optional Nostr transport. Absent means HTTP only.
    #[serde(default)]
    nostr: Option<NostrRequest>,
    mobile: ValidateKeyRequest,
    policy: PolicyRequest,
    hold_seconds: i64,
    recovery_hold_seconds: i64,
    /// Addresses a MOBILE + SERVER recovery spend is allowed to pay. Optional, and empty means
    /// "anywhere" - but it is the single most effective control available on that path, so the
    /// wizard asks for it rather than leaving it to a config file nobody edits.
    ///
    /// The recovery path skips the amount caps by design (its legitimate use is sweeping the
    /// whole balance), `older(N)` is *relative* so mature coins already satisfy it, and that
    /// leaves the hold, the notification and this list. Pre-committing to an address you control
    /// means a stolen phone cannot redirect the funds even if everything else is defeated.
    #[serde(default)]
    recovery_destination_whitelist: Option<Vec<String>>,
    #[serde(default)]
    ntfy_url: Option<String>,
    /// Alternative to ntfy. The config has always supported both; only the browser wizard was
    /// ntfy-only, which forced anyone unwilling to use a third-party push service to give up
    /// on the wizard entirely.
    #[serde(default)]
    smtp: Option<SmtpRequest>,
}

#[derive(Deserialize)]
struct SmtpRequest {
    host: String,
    port: u16,
    username: String,
    password: String,
    from: String,
    to: String,
}

/// Enabling the Nostr transport from the browser.
///
/// The nsec is generated on the box rather than asked for. It is a machine credential - like an
/// SSH host key - not an identity the operator brings: it identifies *this service* so devices
/// can address it and so its replies are attributable. Reusing a personal Nostr key here would
/// hand a server that holds a signing key the ability to post as you, and would tie this
/// wallet's traffic pattern to a public social identity. So the wizard makes one, shows the
/// resulting npub, and never mentions the secret again.
#[derive(Deserialize)]
struct NostrRequest {
    /// Relay URLs to connect outbound to. At least one; more than one is strongly advised.
    relays: Vec<String>,
    /// npubs allowed to submit requests. Each device gets its own, so a lost one is revoked by
    /// deleting a line rather than by rotating a shared secret.
    allowed_npubs: Vec<String>,
}

#[derive(Deserialize)]
struct PolicyRequest {
    max_tx_sat: u64,
    max_daily_sat: u64,
    max_weekly_sat: u64,
    max_monthly_sat: u64,
    max_fee_sat: u64,
    max_fee_rate_sat_per_vb: f64,
}

#[derive(Serialize)]
struct FinishResponse {
    descriptor: String,
    receive_descriptor: String,
    change_descriptor: String,
    first_address: String,
    server_fingerprint: String,
    config_path: String,
    /// The generated bearer token. Shown once, on the final screen - it lives in a 0600 file on
    /// the box, so it is recoverable, but the operator needs it now to configure whatever will
    /// be submitting PSBTs.
    api_token: String,
    /// This service's Nostr identity, if the transport was enabled. The *public* half only: the
    /// nsec is a machine credential that stays on the box and is never shown.
    #[serde(skip_serializing_if = "Option::is_none")]
    nostr_npub: Option<String>,
    /// The multipath descriptor as an inline SVG QR, for carrying to a phone without retyping
    /// it. `None` if the descriptor is too long to encode - the copy/download paths in the UI
    /// always work, so this is a convenience that's allowed to be absent rather than an error.
    descriptor_qr_svg: Option<String>,
    /// The same wallet as a single-path receive descriptor. BIP389 multipath (`<0;1>`) is the
    /// compact form and what this service prefers, but plenty of wallets - Bitcoin Keeper among
    /// them, on the version this was tested against - reject it outright as an unrecognised
    /// format. Offering both turns "your descriptor is broken" into "try the other one".
    receive_qr_svg: Option<String>,
    change_qr_svg: Option<String>,
}

/// Renders `data` as an inline SVG QR, or `None` if it's too long to encode. Callers always
/// show the same payload as selectable text too, so a missing QR degrades to "type it" rather
/// than blocking anything.
pub(crate) fn qr_svg(data: &str) -> Option<String> {
    use qrcode::render::svg;
    use qrcode::{EcLevel, QrCode};

    // Low EC deliberately: these are long strings, the screen showing them is inches away from
    // the camera, and a failed scan is retried for free - whereas overflowing the version cap
    // means no QR at all.
    QrCode::with_error_correction_level(data.as_bytes(), EcLevel::L)
        .ok()
        .map(|code| {
            code.render()
                .min_dimensions(240, 240)
                .dark_color(svg::Color("#000000"))
                .light_color(svg::Color("#ffffff"))
                .build()
        })
}

/// A descriptor key expression: `[fingerprint/derivation]xpub`. This is the standard way to
/// hand a co-signer key to another wallet - a bare xpub loses the key origin, and without it a
/// coordinator cannot build a PSBT this service will recognise as its own.
///
/// The hardened marker is normalised to an apostrophe rather than passed through as written.
/// BIP380 permits both `'` and `h`, but `'` is what is actually accepted everywhere, and it's
/// what `descriptor.rs` emits for the finished wallet descriptor - so emitting `48h/0h/0h/2h`
/// here meant this service handed out the same key in two different notations depending on
/// which screen you were looking at. Parsing and re-displaying via [`DerivationPath`] gets the
/// canonical form for free instead of doing string surgery on whatever was typed in.
fn key_expression(fingerprint: &str, derivation_path: &str, xpub: &str) -> String {
    let fp = fingerprint.trim().to_lowercase();
    let raw = derivation_path
        .trim()
        .trim_start_matches(['m', 'M'])
        .trim_start_matches('/');
    if raw.is_empty() {
        return format!("[{fp}]{}", xpub.trim());
    }
    let path = match raw.parse::<DerivationPath>() {
        Ok(p) => p.to_string(),
        // Unparseable paths can't reach here - every path is validated before a key is
        // accepted - but falling back to the input beats panicking on a display string.
        Err(_) => raw.to_string(),
    };
    format!("[{fp}/{path}]{}", xpub.trim())
}

/// Writes the config. This is the only handler that touches disk, and it is all-or-nothing:
/// the rendered TOML is parsed and validated, and the descriptor is built from it, before
/// anything is written. A config that would fail on `serve` is rejected here instead, while
/// the person who can fix it is still looking at the form.
async fn finish_handler(
    State(state): State<Arc<SetupState>>,
    Json(req): Json<FinishRequest>,
) -> Result<Json<FinishResponse>, SetupError> {
    if state.wallet_toml_path().exists() {
        return Err(SetupError::bad_request(
            "this cosigner is already configured; refusing to overwrite wallet.toml",
        ));
    }

    let network = state.deployment.network;
    let hardware = validate_key(network, &req.hardware)?;
    let mobile = validate_key(network, &req.mobile)?;

    let mut guard = state.generated.lock().await;
    let generated = guard.as_ref().ok_or_else(|| {
        SetupError::bad_request("no SERVER key has been generated yet - go back and generate one")
    })?;

    // The config written must be for the key the operator actually saw and registered.
    //
    // `/api/server-key` can be called more than once - "generate a different key" is a button -
    // and each call replaces the held key. Without this check, registering a key in a wallet app
    // and *then* regenerating would silently write a config for the newer key, producing a
    // descriptor whose SERVER key does not match the one that was registered. The first-address
    // cross-check on the final screen would eventually catch it, but only after the operator had
    // been told everything succeeded.
    if let Some(expected) = req.server_fingerprint.as_deref() {
        let expected = expected.trim().to_lowercase();
        if expected != generated.master_fingerprint {
            return Err(SetupError::bad_request(format!(
                "this page is showing SERVER key {expected}, but the key currently held by the \
                 service is {}. A different key was generated after this page loaded - reload \
                 and register the new one, or generate again",
                generated.master_fingerprint
            )));
        }
    }

    if req.timelock_blocks == 0 {
        return Err(SetupError::bad_request(
            "the recovery timelock must be at least 1 block",
        ));
    }
    // `WalletConfig::validate` enforces this too, but only after the whole form has been
    // filled in. Rejecting it here, with the reason, beats a late failure on a field the UI
    // could plausibly have presented as optional.
    let has_ntfy = req.ntfy_url.as_ref().is_some_and(|s| !s.trim().is_empty());
    let has_smtp = req
        .smtp
        .as_ref()
        .is_some_and(|s| !s.host.trim().is_empty() && !s.to.trim().is_empty());
    if !has_ntfy && !has_smtp {
        return Err(SetupError::bad_request(
            "a notification channel is required - either an ntfy URL or SMTP email. A hold \
             window with no notification channel would wait silently and then sign, with nobody \
             in a position to veto it",
        ));
    }
    // Two distinct keys are the whole point of a multisig; identical xpubs would compile into a
    // descriptor that looks like 2-of-3 but is really 1-of-2.
    if hardware.xpub == mobile.xpub {
        return Err(SetupError::bad_request(
            "the HARDWARE and Bitcoin Keeper keys are the same xpub - each key must be a \
             different device",
        ));
    }
    if hardware.xpub == generated.xpub || mobile.xpub == generated.xpub {
        return Err(SetupError::bad_request(
            "one of the keys you entered is the SERVER key this box just generated",
        ));
    }

    // Generated before the config is rendered, because the config has to reference the file.
    let nostr =
        match req.nostr.as_ref() {
            Some(n) => {
                let relays: Vec<String> = n
                    .relays
                    .iter()
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
                let npubs: Vec<String> = n
                    .allowed_npubs
                    .iter()
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
                if relays.is_empty() {
                    return Err(SetupError::bad_request(
                        "the Nostr transport needs at least one relay",
                    ));
                }
                if npubs.is_empty() {
                    return Err(SetupError::bad_request(
                        "the Nostr transport needs at least one allowed npub - an empty allowlist \
                     accepts requests from nobody, which is a slower way to write \"disabled\"",
                    ));
                }
                let keys = nostr_sdk::Keys::generate();
                let nsec = keys.secret_key().to_bech32().map_err(|e| {
                    SetupError::internal(format!("encoding the generated nsec: {e}"))
                })?;
                let npub = keys.public_key().to_bech32().map_err(|e| {
                    SetupError::internal(format!("encoding the generated npub: {e}"))
                })?;
                Some((relays, npubs, Zeroizing::new(nsec), npub))
            }
            None => None,
        };

    let answers = build_answers(&state.deployment, &req, hardware, mobile, generated, &nostr);
    let toml_text = wizard::render_user_toml(&answers);

    // Parse and validate exactly the bytes about to be written - not the in-memory answers -
    // so a rendering bug surfaces here rather than as a confusing failure on the next start.
    let cfg: WalletConfig = toml::from_str(&toml_text)
        .map_err(|e| SetupError::internal(format!("generated config failed to parse: {e}")))?;
    cfg.validate()
        .map_err(|e| SetupError::bad_request(format!("{e}")))?;

    let built = descriptor::build_descriptor(&cfg).map_err(|e| {
        SetupError::bad_request(format!("these keys don't form a valid wallet: {e}"))
    })?;
    // Receive index 0, from the external chain - the address the UI tells the operator to
    // cross-check against what Bitcoin Keeper shows after importing the descriptor. A mismatch
    // there is the cheapest possible way to catch a mistyped xpub before any coins move.
    let first_address = descriptor::address_at(&built.external, 0, cfg.network)
        .map_err(|e| SetupError::internal(format!("deriving the first address failed: {e}")))?
        .to_string();

    write_private(&state.server_xprv_path(), generated.account_xprv.as_bytes())
        .map_err(|e| SetupError::internal(format!("writing the SERVER key failed: {e}")))?;
    // Written before wallet.toml, same ordering rule as the xprv: the config references this
    // file, so it must never exist pointing at a token that isn't there.
    let api_token = generate_api_token();
    if let Err(e) = write_private(&state.api_token_path(), api_token.as_bytes()) {
        let _ = std::fs::remove_file(state.server_xprv_path());
        return Err(SetupError::internal(format!(
            "writing the API token failed: {e}"
        )));
    }
    if let Some((_, _, nsec, _)) = &nostr {
        if let Err(e) = write_private(&state.nostr_nsec_path(), nsec.as_bytes()) {
            let _ = std::fs::remove_file(state.server_xprv_path());
            let _ = std::fs::remove_file(state.api_token_path());
            return Err(SetupError::internal(format!(
                "writing the Nostr key failed: {e}"
            )));
        }
    }
    // wallet.toml last: its presence is what the entrypoint keys off, so it must never exist
    // without the key file it points at.
    if let Err(e) = write_private(&state.wallet_toml_path(), toml_text.as_bytes()) {
        let _ = std::fs::remove_file(state.server_xprv_path());
        let _ = std::fs::remove_file(state.api_token_path());
        let _ = std::fs::remove_file(state.nostr_nsec_path());
        return Err(SetupError::internal(format!(
            "writing wallet.toml failed: {e}"
        )));
    }

    let multipath = built.multipath.to_string();
    let receive = built.external.to_string();
    let change = built.internal.to_string();
    let response = FinishResponse {
        descriptor_qr_svg: qr_svg(&multipath),
        receive_qr_svg: qr_svg(&receive),
        change_qr_svg: qr_svg(&change),
        descriptor: multipath,
        receive_descriptor: receive,
        change_descriptor: change,
        first_address,
        server_fingerprint: generated.master_fingerprint.clone(),
        config_path: state.wallet_toml_path().display().to_string(),
        api_token,
        nostr_npub: nostr.as_ref().map(|(_, _, _, npub)| npub.clone()),
    };
    // The key is on disk now; drop the in-memory copy.
    *guard = None;
    Ok(Json(response))
}

#[allow(clippy::type_complexity)]
fn build_answers(
    deployment: &Deployment,
    req: &FinishRequest,
    hardware: KeyAnswer,
    mobile: KeyAnswer,
    generated: &GeneratedServerKey,
    nostr: &Option<(Vec<String>, Vec<String>, Zeroizing<String>, String)>,
) -> WizardAnswers {
    WizardAnswers {
        network: deployment.network,
        timelock_blocks: req.timelock_blocks,
        hardware,
        mobile,
        server: KeyAnswer {
            fingerprint: generated.master_fingerprint.clone(),
            derivation_path: generated.derivation_path.clone(),
            xpub: generated.xpub.clone(),
        },
        server_signing: ServerSigningAnswer::File(
            deployment
                .config_dir
                .join(SERVER_XPRV_FILENAME)
                .display()
                .to_string(),
        ),
        // The four fields below are part of [bitcoind]/[server], which `render_user_toml`
        // omits - docker-entrypoint.sh regenerates both sections from the environment on every
        // start. They're populated with the real values anyway so that `WizardAnswers` always
        // describes the actual deployment, rather than carrying placeholders that would be
        // wrong if this struct were ever rendered in full.
        bitcoind_rpc_url: deployment.bitcoind_rpc_url.clone(),
        bitcoind_auth: BitcoindAuthAnswer::UserPass(String::new(), String::new()),
        bind_addr: deployment.bind_addr.clone(),
        gap_limit: 1000,
        ledger_db_path: deployment
            .data_dir
            .join("ledger.sqlite3")
            .display()
            .to_string(),
        policy: PolicyAnswer {
            max_tx_sat: req.policy.max_tx_sat,
            max_daily_sat: req.policy.max_daily_sat,
            max_weekly_sat: req.policy.max_weekly_sat,
            max_monthly_sat: req.policy.max_monthly_sat,
            max_fee_sat: req.policy.max_fee_sat,
            max_fee_rate_sat_per_vb: req.policy.max_fee_rate_sat_per_vb,
            destination_whitelist: None,
        },
        notify: NotifyAnswer {
            hold_seconds: req.hold_seconds,
            sweep_interval_seconds: 30,
            renotify_interval_seconds: 3600,
            ntfy_url: req
                .ntfy_url
                .as_ref()
                .map(|s| s.trim())
                .filter(|s| !s.is_empty())
                .map(|s| s.to_string()),
            ntfy_auth_token: None,
            smtp: req.smtp.as_ref().map(|s| crate::wizard::SmtpAnswer {
                host: s.host.trim().to_string(),
                port: s.port,
                username: s.username.trim().to_string(),
                password: s.password.clone(),
                from: s.from.trim().to_string(),
                to: s.to.trim().to_string(),
            }),
        },
        recovery_hold_seconds: req.recovery_hold_seconds,
        recovery_destination_whitelist: req
            .recovery_destination_whitelist
            .as_ref()
            .map(|addrs| {
                addrs
                    .iter()
                    .map(|a| a.trim().to_string())
                    .filter(|a| !a.is_empty())
                    .collect::<Vec<_>>()
            })
            .filter(|addrs| !addrs.is_empty()),
        nostr_transport: nostr.as_ref().map(|(relays, npubs, _, _)| {
            crate::wizard::NostrTransportAnswer {
                // A file, not an env var: the entrypoint regenerates [server]/[bitcoind] from
                // the environment on every start, but secrets live beside server.xprv where
                // they are written once and only ever read.
                nsec: crate::wizard::NostrNsecAnswer::File(
                    deployment
                        .config_dir
                        .join(NOSTR_NSEC_FILENAME)
                        .display()
                        .to_string(),
                ),
                relays: relays.clone(),
                allowed_npubs: npubs.clone(),
            }
        }),
    }
}

/// A fresh bearer token for `/inspect` and `/sign_psbt`: 256 bits from the same OS CSPRNG the
/// SERVER key comes from, hex-encoded so it survives being copied through a phone, a QR, or a
/// shell without any quoting or encoding questions.
fn generate_api_token() -> String {
    let mut bytes = Zeroizing::new([0u8; 32]);
    bitcoin::secp256k1::rand::rngs::OsRng.fill_bytes(bytes.as_mut());
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Writes owner-read/write only, and creates with those permissions rather than relaxing them
/// afterwards - so the file is never briefly world-readable, even for an instant.
fn write_private(path: &Path, contents: &[u8]) -> Result<()> {
    use std::io::Write;
    use std::os::unix::fs::OpenOptionsExt;

    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(path)
        .with_context(|| format!("creating {}", path.display()))?;
    f.write_all(contents)
        .with_context(|| format!("writing {}", path.display()))?;
    f.sync_all()
        .with_context(|| format!("flushing {} to disk", path.display()))?;
    Ok(())
}

#[derive(Serialize)]
struct DecodeQrResponse {
    /// Every distinct payload found in the image, in the order the decoder returned them.
    payloads: Vec<String>,
    /// Best-effort interpretation of the first payload as a key, so the UI can fill all three
    /// fields from one scan instead of making the operator split it up by hand.
    key: Option<ScannedKey>,
}

#[derive(Serialize)]
struct ScannedKey {
    fingerprint: Option<String>,
    derivation_path: Option<String>,
    xpub: String,
}

/// Decodes a QR from an uploaded image.
///
/// This exists because the browser can't do it here. Both `getUserMedia` (camera) and
/// `BarcodeDetector` require a secure context, and this app is served over plain HTTP on a LAN
/// hostname, so live camera scanning is unavailable in every mainstream browser. Photographing
/// the QR with the phone's normal camera app and uploading the picture works regardless of
/// browser, transport, or platform - and it's the difference between scanning a 111-character
/// xpub and retyping it.
async fn decode_qr_handler(body: axum::body::Bytes) -> Result<Json<DecodeQrResponse>, SetupError> {
    // Generous but bounded: modern phone photos are a few MB, and decoding is CPU-bound on a
    // box that may be busy.
    const MAX_IMAGE_BYTES: usize = 12 * 1024 * 1024;
    if body.is_empty() {
        return Err(SetupError::bad_request("no image was uploaded"));
    }
    if body.len() > MAX_IMAGE_BYTES {
        return Err(SetupError::bad_request(
            "that image is larger than 12 MB - try a screenshot, or a lower-resolution photo",
        ));
    }

    let payloads = tokio::task::spawn_blocking(move || decode_qr_bytes(&body))
        .await
        .map_err(|e| SetupError::internal(format!("decoding panicked: {e}")))?
        .map_err(|e| SetupError::bad_request(format!("{e}")))?;

    if payloads.is_empty() {
        return Err(SetupError::bad_request(
            "no QR code found in that image - make sure the whole code is in frame and in focus",
        ));
    }
    let key = payloads.first().and_then(|p| parse_scanned_key(p));
    Ok(Json(DecodeQrResponse { payloads, key }))
}

fn decode_qr_bytes(bytes: &[u8]) -> Result<Vec<String>> {
    let img = image::load_from_memory(bytes)
        .context("that file doesn't look like a PNG, JPEG or WebP image")?
        .to_luma8();
    let mut prepared = rqrr::PreparedImage::prepare(img);
    let mut out = Vec::new();
    for grid in prepared.detect_grids() {
        if let Ok((_meta, content)) = grid.decode() {
            if !content.is_empty() && !out.contains(&content) {
                out.push(content);
            }
        }
    }
    Ok(out)
}

/// Pulls a key out of whatever a wallet happened to put in its QR. Handles the three shapes
/// seen in practice: a descriptor key expression with origin, a bare xpub, and a JSON export
/// (Coldcard's shape and the variations on it). Returns `None` rather than guessing wildly -
/// the operator can always fall back to typing, and a wrong auto-fill is worse than none.
fn parse_scanned_key(payload: &str) -> Option<ScannedKey> {
    let s = payload.trim();

    // 1. `[fingerprint/derivation]xpub...` - possibly with a trailing `/<0;1>/*` from a full
    //    descriptor fragment, which is not part of the account xpub.
    if let Some(rest) = s.strip_prefix('[') {
        if let Some((origin, tail)) = rest.split_once(']') {
            let (fp, path) = match origin.split_once('/') {
                Some((fp, path)) => (fp, Some(path.to_string())),
                None => (origin, None),
            };
            let xpub = tail.split('/').next().unwrap_or(tail).trim().to_string();
            if !xpub.is_empty() {
                return Some(ScannedKey {
                    fingerprint: Some(fp.trim().to_lowercase()),
                    derivation_path: path,
                    xpub,
                });
            }
        }
    }

    // 2. A JSON export. Look for an xpub and an origin wherever they happen to live, rather
    //    than committing to one vendor's exact schema.
    if s.starts_with('{') {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(s) {
            let fp = ["xfp", "master_fingerprint", "fingerprint"]
                .iter()
                .find_map(|k| v.get(*k).and_then(|x| x.as_str()))
                .map(|f| f.trim().to_lowercase());
            // Prefer the P2WSH-multisig account, which is what this wallet uses.
            let section = ["p2wsh", "bip48_2", "p2wsh_multisig"]
                .iter()
                .find_map(|k| v.get(*k))
                .unwrap_or(&v);
            let xpub = ["xpub", "_pub", "Zpub", "zpub"]
                .iter()
                .find_map(|k| section.get(*k).and_then(|x| x.as_str()))?;
            let deriv = ["deriv", "derivation", "path", "derivation_path"]
                .iter()
                .find_map(|k| section.get(*k).and_then(|x| x.as_str()))
                .map(|d| {
                    d.trim()
                        .trim_start_matches(['m', 'M'])
                        .trim_start_matches('/')
                        .to_string()
                });
            return Some(ScannedKey {
                fingerprint: fp,
                derivation_path: deriv,
                xpub: xpub.trim().to_string(),
            });
        }
    }

    // 3. A bare extended key, with nothing else in the payload.
    let bare = s.split_whitespace().next().unwrap_or(s);
    if bare.len() > 100
        && bare.chars().all(|c| c.is_ascii_alphanumeric())
        && [
            "xpub", "tpub", "ypub", "zpub", "Vpub", "Zpub", "upub", "vpub",
        ]
        .iter()
        .any(|p| bare.starts_with(p))
    {
        return Some(ScannedKey {
            fingerprint: None,
            derivation_path: None,
            xpub: bare.to_string(),
        });
    }

    None
}

/// Shuts the setup server down so the container restarts into `cosigner serve`.
async fn start_handler(State(state): State<Arc<SetupState>>) -> Result<StatusCode, SetupError> {
    if !state.wallet_toml_path().exists() {
        return Err(SetupError::bad_request(
            "setup hasn't been completed yet - there's no config to start with",
        ));
    }
    if let Some(tx) = state.shutdown.lock().await.take() {
        let _ = tx.send(());
    }
    Ok(StatusCode::ACCEPTED)
}

/// BIP48 script-type-2 (P2WSH multisig) account path, with the network's registered SLIP44
/// coin type: 0' on mainnet, 1' on every test chain.
fn default_derivation_path(network: ChainNetwork) -> String {
    let coin_type = match network {
        ChainNetwork::Mainnet => "0h",
        ChainNetwork::Testnet | ChainNetwork::Signet | ChainNetwork::Regtest => "1h",
    };
    format!("48h/{coin_type}/0h/2h")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The same key, expressed as the wizard's request shape.
    fn key_answer(spec: &crate::config::KeySpec) -> KeyAnswer {
        KeyAnswer {
            fingerprint: spec.master_fingerprint.clone(),
            derivation_path: spec.derivation_path.clone(),
            xpub: spec.xpub.clone(),
        }
    }

    /// The wizard's device-compatibility gate, end to end through the HTTP layer: the pairing
    /// this project was built around must come back blocked, with an acknowledgement that states
    /// the real consequence rather than a softened one.
    #[tokio::test]
    async fn the_compat_endpoint_blocks_the_satochip_keeper_pairing() {
        use axum::body::Body;
        use axum::http::Request;
        use http_body_util::BodyExt;
        use tower::ServiceExt;

        let (tx, _rx) = oneshot::channel();
        let state = Arc::new(SetupState::new(deployment(ChainNetwork::Signet), tx));
        let app = router(state);

        let response = app
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/api/compat/resolve")
                    .header("content-type", "application/json")
                    .body(Body::from(
                        r#"{"hardware":"satochip","coordinator":"bitcoin-keeper"}"#,
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);

        let bytes = response.into_body().collect().await.unwrap().to_bytes();
        let json: serde_json::Value = serde_json::from_slice(&bytes).unwrap();

        assert_eq!(json["resolution"]["overall"], "blocked");
        let ack = json["acknowledgement"].as_str().expect("must warn");
        assert!(
            ack.contains("may be unable to spend"),
            "the gate must state the real consequence: {ack}"
        );

        // Every device is offered, none filtered out, and the workable ones come first.
        let options = json["options"].as_array().expect("options present");
        assert!(
            options.len() >= 5,
            "nothing may be hidden from the operator"
        );
        assert_eq!(options[0]["verdict"], "ok");
    }

    /// A complete, valid wizard submission - the baseline each test then varies one field of.
    fn finish_request(
        hardware: &crate::config::KeySpec,
        mobile: &crate::config::KeySpec,
    ) -> FinishRequest {
        let as_request = |spec: &crate::config::KeySpec| ValidateKeyRequest {
            fingerprint: spec.master_fingerprint.clone(),
            derivation_path: spec.derivation_path.clone(),
            xpub: spec.xpub.clone(),
        };
        FinishRequest {
            timelock_blocks: 12960,
            hardware: as_request(hardware),
            server_fingerprint: None,
            nostr: None,
            mobile: as_request(mobile),
            policy: PolicyRequest {
                max_tx_sat: 100_000,
                max_daily_sat: 200_000,
                max_weekly_sat: 500_000,
                max_monthly_sat: 1_000_000,
                max_fee_sat: 10_000,
                max_fee_rate_sat_per_vb: 50.0,
            },
            hold_seconds: 3600,
            recovery_hold_seconds: 86400,
            recovery_destination_whitelist: None,
            ntfy_url: Some("https://ntfy.sh/bitme-test-topic".to_string()),
            smtp: None,
        }
    }

    fn deployment(network: ChainNetwork) -> Deployment {
        Deployment {
            network,
            config_dir: PathBuf::from("/data/config"),
            data_dir: PathBuf::from("/data"),
            bind_addr: "0.0.0.0:8080".to_string(),
            bitcoind_rpc_url: "http://10.21.21.8:8332".to_string(),
        }
    }

    /// The escape address is the strongest control on the MOBILE + SERVER path - that path skips
    /// the amount caps by design, and `older(N)` is relative so mature coins already satisfy it.
    /// The wizard collecting it has to actually reach the config, or it is theatre.
    #[test]
    fn a_recovery_whitelist_from_the_wizard_reaches_the_rendered_config() {
        let network = ChainNetwork::Signet;
        let (hardware, _) = crate::test_util::test_key_spec_with_xpriv(1);
        let (mobile, _) = crate::test_util::test_key_spec_with_xpriv(2);
        let path = default_derivation_path(network);
        let generated = generate_server_key(network, &path, None).expect("generation");
        // A real signet address - `RecoveryConfig::validate` network-checks these, so a
        // placeholder would be rejected rather than round-tripped.
        let escape = "tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx";

        let mut req = finish_request(&hardware, &mobile);
        req.recovery_destination_whitelist = Some(vec![
            format!("  {escape}  "),
            String::new(),
            "\t".to_string(),
        ]);

        let answers = build_answers(
            &deployment(network),
            &req,
            key_answer(&hardware),
            key_answer(&mobile),
            &generated,
            &None,
        );
        // Blank entries are dropped and surrounding whitespace trimmed, so a trailing newline in
        // the textarea doesn't become an unparseable address.
        assert_eq!(
            answers.recovery_destination_whitelist,
            Some(vec![escape.to_string()])
        );

        let text = wizard::render_user_toml(&answers);
        assert!(text.contains(escape), "rendered:\n{text}");
        let cfg: WalletConfig = toml::from_str(&text).expect("should parse");
        cfg.validate().expect("should validate");
        assert_eq!(
            cfg.recovery_config()
                .compiled_whitelist(network)
                .expect("whitelist compiles")
                .map(|w| w.len()),
            Some(1)
        );
    }

    /// An empty or whitespace-only textarea must mean "no whitelist", not "a whitelist containing
    /// an empty string" - which would compile to a list nothing can satisfy and brick recovery.
    #[test]
    fn a_blank_recovery_whitelist_is_treated_as_unset() {
        let network = ChainNetwork::Signet;
        let (hardware, _) = crate::test_util::test_key_spec_with_xpriv(1);
        let (mobile, _) = crate::test_util::test_key_spec_with_xpriv(2);
        let path = default_derivation_path(network);
        let generated = generate_server_key(network, &path, None).expect("generation");

        for blank in [Some(vec![]), Some(vec!["   ".to_string()]), None] {
            let mut req = finish_request(&hardware, &mobile);
            req.recovery_destination_whitelist = blank.clone();
            let answers = build_answers(
                &deployment(network),
                &req,
                key_answer(&hardware),
                key_answer(&mobile),
                &generated,
                &None,
            );
            assert_eq!(
                answers.recovery_destination_whitelist, None,
                "blank input {blank:?} must not become a whitelist"
            );
        }
    }

    /// The Nostr section the wizard renders has to be one `serve` will actually accept -
    /// otherwise enabling it in the browser produces a config that fails on the next start,
    /// which on Umbrel is a crash-loop with no UI left to fix it from.
    #[test]
    fn a_wizard_configured_nostr_transport_renders_a_config_that_validates() {
        let network = ChainNetwork::Signet;
        let (hardware, _) = crate::test_util::test_key_spec_with_xpriv(1);
        let (mobile, _) = crate::test_util::test_key_spec_with_xpriv(2);
        let path = default_derivation_path(network);
        let generated = generate_server_key(network, &path, None).expect("generation");

        // A real npub, so the bech32 check in `NostrTransportConfig::validate` is exercised
        // rather than sidestepped by a placeholder.
        let device = nostr_sdk::Keys::generate()
            .public_key()
            .to_bech32()
            .unwrap();
        let service = nostr_sdk::Keys::generate();
        let nostr = Some((
            vec!["wss://relay.damus.io".to_string()],
            vec![device.clone()],
            Zeroizing::new(service.secret_key().to_bech32().unwrap()),
            service.public_key().to_bech32().unwrap(),
        ));

        let answers = build_answers(
            &deployment(network),
            &finish_request(&hardware, &mobile),
            key_answer(&hardware),
            key_answer(&mobile),
            &generated,
            &nostr,
        );
        let text = wizard::render_user_toml(&answers);
        assert!(text.contains("[nostr_transport]"), "rendered:\n{text}");
        assert!(
            text.contains(&device),
            "the allowed npub must reach the config"
        );
        assert!(
            text.contains("nostr.nsec"),
            "the config must point at the generated key file, not inline the secret"
        );
        assert!(
            !text.contains("nsec1"),
            "the secret key must never be written into wallet.toml:\n{text}"
        );

        let cfg: WalletConfig = toml::from_str(&text).expect("should parse");
        cfg.validate().expect("should validate");
    }

    #[test]
    fn default_path_uses_the_registered_coin_type_per_network() {
        assert_eq!(
            default_derivation_path(ChainNetwork::Mainnet),
            "48h/0h/0h/2h"
        );
        assert_eq!(
            default_derivation_path(ChainNetwork::Signet),
            "48h/1h/0h/2h"
        );
        assert_eq!(
            default_derivation_path(ChainNetwork::Regtest),
            "48h/1h/0h/2h"
        );
        assert_eq!(
            default_derivation_path(ChainNetwork::Testnet),
            "48h/1h/0h/2h"
        );
    }

    #[test]
    fn generated_server_key_matches_its_own_xpub_and_path() {
        let network = ChainNetwork::Signet;
        let path = default_derivation_path(network);
        let g = generate_server_key(network, &path, None).expect("generation should succeed");

        // The xprv written to disk must be the account key the config's xpub names - this is
        // exactly the equality `ServerSigningKey::load` refuses to start without.
        let secp = Secp256k1::new();
        let account: Xpriv = g.account_xprv.parse().expect("account xprv should parse");
        let derived = Xpub::from_priv(&secp, &account).to_string();
        assert_eq!(derived, g.xpub);

        // And the xpub must sit at the declared depth, or `KeySpec::validate` rejects it.
        let xpub: Xpub = g.xpub.parse().expect("xpub should parse");
        let depth = path.parse::<DerivationPath>().expect("path parses").len();
        assert_eq!(xpub.depth as usize, depth);
    }

    /// The key handed out on the setup screen and the key inside the finished descriptor must
    /// be byte-identical, notation included. They were not: `key_expression` passed the
    /// configured path through verbatim (`48h/1h/0h/2h`) while `descriptor.rs` emits the
    /// canonical apostrophe form, so this service advertised the same key two different ways.
    #[test]
    fn key_expression_notation_matches_the_descriptor() {
        let expr = key_expression("AB12CD34", "48h/1h/0h/2h", "tpubEXAMPLE");
        assert_eq!(expr, "[ab12cd34/48'/1'/0'/2']tpubEXAMPLE");
        assert!(
            !expr.contains('h'),
            "hardened marker must be an apostrophe: {expr}"
        );

        // Already-canonical input is left alone, and `m/` prefixes are stripped.
        assert_eq!(
            key_expression("ab12cd34", "48'/1'/0'/2'", "tpubEXAMPLE"),
            "[ab12cd34/48'/1'/0'/2']tpubEXAMPLE"
        );
        assert_eq!(
            key_expression("ab12cd34", "m/48h/1h/0h/2h", "tpubEXAMPLE"),
            "[ab12cd34/48'/1'/0'/2']tpubEXAMPLE"
        );
    }

    /// End to end: the origin the wizard shows for the SERVER key has to be exactly the origin
    /// that ends up in the descriptor a coordinator imports, or the coordinator builds PSBTs
    /// this service won't recognise as its own.
    #[test]
    fn advertised_server_key_appears_verbatim_in_the_built_descriptor() {
        let network = ChainNetwork::Signet;
        let path = default_derivation_path(network);
        let g = generate_server_key(network, &path, None).expect("generation");
        let advertised = key_expression(&g.master_fingerprint, &g.derivation_path, &g.xpub);

        let (hardware, _) = crate::test_util::test_key_spec_with_xpriv(1);
        let (mobile, _) = crate::test_util::test_key_spec_with_xpriv(2);
        let mut cfg = crate::test_util::test_wallet_config(144);
        cfg.network = network;
        cfg.keys.hardware = hardware;
        cfg.keys.mobile = mobile;
        cfg.keys.server = crate::config::KeySpec {
            master_fingerprint: g.master_fingerprint.clone(),
            derivation_path: g.derivation_path.clone(),
            xpub: g.xpub.clone(),
        };

        let built = descriptor::build_descriptor(&cfg).expect("descriptor should build");
        let desc = built.multipath.to_string();
        let origin = advertised.split(']').next().expect("has an origin");
        assert!(
            desc.contains(origin),
            "descriptor does not contain the advertised origin\n  advertised: {origin}]\n  descriptor: {desc}"
        );
    }

    /// Supplied entropy must *change* the key - if it were accepted and then ignored, the UI
    /// would be reporting a protection that doesn't exist, which is worse than not offering it.
    #[test]
    fn user_entropy_changes_the_derived_key() {
        let path = default_derivation_path(ChainNetwork::Signet);
        let dice = "4 2 6 1 3 5 5 2 6 1 4 3 2 5 1 6 3 4 2 5 1 6 4 3";

        let a = generate_server_key(ChainNetwork::Signet, &path, Some(dice)).expect("a");
        let b = generate_server_key(ChainNetwork::Signet, &path, Some(dice)).expect("b");
        // Same user entropy, different OS bytes - so still different keys. The OS contribution
        // is not being discarded in favour of what was typed.
        assert_ne!(
            a.xpub, b.xpub,
            "identical user entropy must not produce a reproducible key - the OS bytes are \
             mixed in, not replaced"
        );

        let plain = generate_server_key(ChainNetwork::Signet, &path, None).expect("plain");
        assert_ne!(a.xpub, plain.xpub);

        // The mixed key is still a well-formed account key at the declared depth.
        let xpub: Xpub = a.xpub.parse().expect("xpub parses");
        assert_eq!(
            xpub.depth as usize,
            path.parse::<DerivationPath>().unwrap().len()
        );
        let secp = Secp256k1::new();
        let account: Xpriv = a.account_xprv.parse().expect("account xprv parses");
        assert_eq!(Xpub::from_priv(&secp, &account).to_string(), a.xpub);
    }

    /// The mix is `SHA256(tag || os || user)`. Pinning it against an independently computed
    /// digest means a refactor cannot silently change what the entropy is, or drop one of the
    /// inputs while still producing a plausible-looking key.
    #[test]
    fn the_entropy_mix_is_exactly_the_documented_construction() {
        use bitcoin::hashes::{sha256, Hash, HashEngine};

        let os_bytes = [0xABu8; 32];
        let user = "some dice rolls";

        let mut engine = sha256::Hash::engine();
        engine.input(ENTROPY_MIX_TAG);
        engine.input(&os_bytes);
        engine.input(user.as_bytes());
        let expected = sha256::Hash::from_engine(engine).to_byte_array();

        // Both inputs must actually be present: dropping either changes the result.
        let mut without_user = sha256::Hash::engine();
        without_user.input(ENTROPY_MIX_TAG);
        without_user.input(&os_bytes);
        assert_ne!(
            sha256::Hash::from_engine(without_user).to_byte_array(),
            expected
        );

        let mut without_os = sha256::Hash::engine();
        without_os.input(ENTROPY_MIX_TAG);
        without_os.input(user.as_bytes());
        assert_ne!(
            sha256::Hash::from_engine(without_os).to_byte_array(),
            expected
        );
    }

    #[test]
    fn two_generated_keys_are_never_the_same() {
        let path = default_derivation_path(ChainNetwork::Signet);
        let a = generate_server_key(ChainNetwork::Signet, &path, None).expect("first");
        let b = generate_server_key(ChainNetwork::Signet, &path, None).expect("second");
        assert_ne!(a.xpub, b.xpub);
        assert_ne!(a.master_fingerprint, b.master_fingerprint);
    }

    #[test]
    fn generated_key_is_on_the_requested_network() {
        for network in [
            ChainNetwork::Mainnet,
            ChainNetwork::Signet,
            ChainNetwork::Regtest,
        ] {
            let path = default_derivation_path(network);
            let g = generate_server_key(network, &path, None).expect("generation should succeed");
            let xpub: Xpub = g.xpub.parse().expect("xpub parses");
            assert_eq!(xpub.network, network.xpub_network_kind());
        }
    }

    /// The web wizard must not emit `[bitcoind]`/`[server]`: docker-entrypoint.sh appends its
    /// own copies of both on every start, and TOML rejects a duplicated table, so emitting
    /// them here would make the container fail to start immediately after setup.
    #[test]
    fn rendered_config_omits_the_sections_the_entrypoint_generates() {
        let network = ChainNetwork::Signet;
        let (hardware, _) = crate::test_util::test_key_spec_with_xpriv(1);
        let (mobile, _) = crate::test_util::test_key_spec_with_xpriv(2);
        let path = default_derivation_path(network);
        let generated = generate_server_key(network, &path, None).expect("generation");

        let req = finish_request(&hardware, &mobile);

        let answers = build_answers(
            &deployment(network),
            &req,
            key_answer(&hardware),
            key_answer(&mobile),
            &generated,
            &None,
        );
        let text = wizard::render_user_toml(&answers);
        assert!(!text.contains("[bitcoind]"), "rendered:\n{text}");
        assert!(!text.contains("[server]"), "rendered:\n{text}");
        assert!(text.contains("[server_signing]"), "rendered:\n{text}");

        // ...and what it does emit has to be a config the service would accept.
        let cfg: WalletConfig = toml::from_str(&text).expect("should parse");
        cfg.validate().expect("should validate");
        descriptor::build_descriptor(&cfg).expect("should build a descriptor");
    }
}
